import type { Patient } from '@/lib/types';

export async function generatePatientPDF(patients: Patient[], reportedBy = 'Sentinel ICU System') {
  const { default: jsPDF } = await import('jspdf');
  const { default: autoTable } = await import('jspdf-autotable');

  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const W = doc.internal.pageSize.getWidth();
  const H = doc.internal.pageSize.getHeight();
  const now = new Date();
  const ts =
    now.toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' }) +
    ', ' +
    now.toLocaleTimeString('en-IN', { hour: '2-digit', minute: '2-digit' });

  // Colour palette  (R,G,B tuples)
  type RGB = [number, number, number];
  const C_BLUE: RGB = [30, 64, 175];
  const C_RED: RGB = [185, 28, 28];
  const C_AMBER: RGB = [161, 98, 7];
  const C_GREEN: RGB = [21, 128, 61];
  const C_DARK: RGB = [15, 23, 42];
  const C_CARD: RGB = [22, 33, 62];
  const C_MUTED: RGB = [100, 116, 139];
  const C_LIGHT: RGB = [226, 232, 240];
  const C_WHITE: RGB = [255, 255, 255];
  const C_SLATE: RGB = [30, 41, 59];

  const statusRGB = (s: string): RGB =>
    s === 'critical' || s === 'code'
      ? C_RED
      : s === 'warning'
        ? C_AMBER
        : s === 'watch'
          ? C_BLUE
          : C_GREEN;

  const riskRGB = (r: number): RGB => (r >= 70 ? C_RED : r >= 40 ? C_AMBER : C_GREEN);

  /* ── Helpers ──────────────────────────────────────────────────── */
  const wardLabel = (id: string) =>
    id
      .replace('ward-icu-a', 'ICU Alpha')
      .replace('ward-icu-b', 'ICU Beta')
      .replace('ward-icu-c', 'ICU Gamma')
      .replace('ward-icu-d', 'Cardiac ICU')
      .replace('ward-icu-e', 'Neuro ICU')
      .toUpperCase();

  function header(page: number, total: number) {
    // Top bar
    doc.setFillColor(...C_BLUE);
    doc.rect(0, 0, W, 24, 'F');

    // Logo box
    doc.setFillColor(...C_WHITE);
    doc.roundedRect(8, 5, 14, 14, 2, 2, 'F');
    doc.setFontSize(8);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...C_BLUE);
    doc.text('ICU', 15, 14, { align: 'center' });

    // Title
    doc.setTextColor(...C_WHITE);
    doc.setFontSize(12);
    doc.text('PROJECT SENTINEL', 26, 11);
    doc.setFontSize(7);
    doc.setFont('helvetica', 'normal');
    doc.text('ICU Monitoring & Intelligence Platform', 26, 17);

    // Right meta
    doc.setFontSize(7);
    doc.setTextColor(180, 210, 255);
    doc.text(`Generated: ${ts}`, W - 8, 9, { align: 'right' });
    doc.text(`Reported by: ${reportedBy}`, W - 8, 14, { align: 'right' });
    doc.text(`Page ${page} of ${total}`, W - 8, 19, { align: 'right' });

    // CONFIDENTIAL pill
    doc.setFillColor(...C_RED);
    doc.roundedRect(W - 52, 3, 26, 6, 1.5, 1.5, 'F');
    doc.setFontSize(5.5);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...C_WHITE);
    doc.text('CONFIDENTIAL', W - 39, 7, { align: 'center' });
  }

  function footer() {
    doc.setFillColor(241, 245, 249);
    doc.rect(0, H - 9, W, 9, 'F');
    doc.setFontSize(5.5);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...C_MUTED);
    doc.text(
      'This report is generated by Project Sentinel ICU Platform and contains sensitive protected health information (PHI). Unauthorised disclosure is prohibited.',
      8,
      H - 4
    );
  }

  const totalPages = patients.length + 1;

  /* ══════════════════════════════════════════════════════════════════
     COVER PAGE
  ══════════════════════════════════════════════════════════════════ */
  // Background
  doc.setFillColor(...C_DARK);
  doc.rect(0, 0, W, H, 'F');
  header(1, totalPages);

  // Left accent stripe
  doc.setFillColor(...C_BLUE);
  doc.rect(0, 24, 3, H - 33, 'F');

  // Title card
  doc.setFillColor(...C_CARD);
  doc.roundedRect(10, 30, W - 20, 48, 3, 3, 'F');
  doc.setFillColor(...C_BLUE);
  doc.roundedRect(10, 30, W - 20, 4, 3, 3, 'F'); // top accent line

  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...C_WHITE);
  doc.text('Patient Clinical Report', W / 2, 50, { align: 'center' });

  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...C_MUTED);
  doc.text(
    `Comprehensive clinical summary for ${patients.length} patient${patients.length !== 1 ? 's' : ''}`,
    W / 2,
    59,
    { align: 'center' }
  );
  doc.text(`Report Date: ${ts}`, W / 2, 66, { align: 'center' });
  doc.text(`Authorised by: ${reportedBy}`, W / 2, 73, { align: 'center' });

  // ── Stats grid ──────────────────────────────────────────────────
  const critical = patients.filter((p) => p.status === 'critical' || p.status === 'code').length;
  const warning = patients.filter((p) => p.status === 'warning').length;
  const stable = patients.filter((p) => p.status === 'stable').length;
  const avgN2 = Math.round(patients.reduce((s, p) => s + (p.news2 || 0), 0) / patients.length);
  const avgRisk = Math.round(
    patients.reduce((s, p) => s + (p.aiRiskScore || 0), 0) / patients.length
  );

  const stats = [
    { label: 'Total Patients', val: String(patients.length), rgb: C_BLUE },
    { label: 'Critical', val: String(critical), rgb: C_RED },
    { label: 'Warning', val: String(warning), rgb: C_AMBER },
    { label: 'Stable', val: String(stable), rgb: C_GREEN },
    { label: 'Avg NEWS2', val: String(avgN2), rgb: C_BLUE },
    { label: 'Avg AI Risk', val: `${avgRisk}%`, rgb: riskRGB(avgRisk) },
  ];

  const colW = (W - 20) / 3;
  stats.forEach((s, i) => {
    const cx = 10 + (i % 3) * colW;
    const cy = 86 + Math.floor(i / 3) * 22;
    doc.setFillColor(...C_SLATE);
    doc.roundedRect(cx + 1, cy, colW - 2, 19, 2, 2, 'F');
    doc.setFontSize(15);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...s.rgb);
    doc.text(s.val, cx + colW / 2, cy + 11, { align: 'center' });
    doc.setFontSize(6.5);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...C_MUTED);
    doc.text(s.label, cx + colW / 2, cy + 16, { align: 'center' });
  });

  // ── Patient index table ─────────────────────────────────────────
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...C_LIGHT);
  doc.text('Patient Index', 12, 136);

  autoTable(doc, {
    startY: 139,
    head: [['#', 'Patient Name', 'Age / Gender', 'Diagnosis', 'Bed', 'Status', 'NEWS2', 'AI Risk']],
    body: patients.map((p, i) => [
      i + 1,
      p.name,
      `${p.age}y / ${p.gender === 'M' ? 'Male' : p.gender === 'F' ? 'Female' : 'Other'}`,
      p.diagnosis,
      (p.bedId || '-').toUpperCase(),
      p.status.toUpperCase(),
      p.news2 ?? '-',
      `${p.aiRiskScore ?? 0}%`,
    ]),
    styles: {
      fontSize: 7.5,
      cellPadding: 2.5,
      textColor: C_LIGHT,
      fillColor: C_CARD,
      lineColor: [51, 65, 85],
      lineWidth: 0.25,
    },
    headStyles: { fillColor: C_BLUE, textColor: C_WHITE, fontStyle: 'bold', fontSize: 7.5 },
    alternateRowStyles: { fillColor: C_SLATE },
    columnStyles: {
      0: { cellWidth: 8, halign: 'center' },
      5: { halign: 'center' },
      6: { halign: 'center' },
      7: { halign: 'center' },
    },
    didParseCell: (data) => {
      if (data.section === 'body' && data.column.index === 5) {
        const s = (data.cell.raw as string).toLowerCase();
        data.cell.styles.textColor =
          s.includes('critical') || s.includes('code')
            ? [252, 165, 165]
            : s.includes('warning')
              ? [253, 186, 116]
              : s.includes('watch')
                ? [147, 197, 253]
                : [110, 231, 183];
        data.cell.styles.fontStyle = 'bold';
      }
    },
    margin: { left: 12, right: 12 },
  });

  footer();

  /* ══════════════════════════════════════════════════════════════════
     PER-PATIENT PAGES
  ══════════════════════════════════════════════════════════════════ */
  patients.forEach((p, idx) => {
    doc.addPage();
    const v = p.vitals || {};

    doc.setFillColor(...C_DARK);
    doc.rect(0, 0, W, H, 'F');
    header(idx + 2, totalPages);

    // Left status stripe
    const sc = statusRGB(p.status);
    doc.setFillColor(...sc);
    doc.rect(0, 24, 3, H - 33, 'F');

    let y = 29;

    /* Identity card */
    doc.setFillColor(...C_CARD);
    doc.roundedRect(6, y, W - 12, 34, 2, 2, 'F');

    // Avatar circle
    doc.setFillColor(...C_BLUE);
    doc.circle(21, y + 17, 11, 'F');
    const initials = p.name
      .split(' ')
      .map((n: string) => n[0])
      .join('')
      .slice(0, 2)
      .toUpperCase();
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...C_WHITE);
    doc.text(initials, 21, y + 20.5, { align: 'center' });

    // Name + demog
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...C_WHITE);
    doc.text(p.name, 36, y + 10);

    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...C_MUTED);
    doc.text(
      `${p.age} years  |  ${p.gender === 'M' ? 'Male' : p.gender === 'F' ? 'Female' : 'Other'}  |  ID: ${p.id}`,
      36,
      y + 18
    );
    doc.text(
      `Admitted: ${p.admissionDate || '-'}  |  Bed: ${(p.bedId || '-').toUpperCase()}  |  Ward: ${wardLabel(p.wardId || '')}`,
      36,
      y + 26
    );

    // Status pill
    doc.setFillColor(...sc);
    doc.roundedRect(W - 40, y + 11, 32, 9, 2, 2, 'F');
    doc.setFontSize(7.5);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...C_WHITE);
    doc.text(p.status.toUpperCase(), W - 24, y + 17, { align: 'center' });

    y += 39;

    /* Clinical Summary */
    doc.setFontSize(8);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(147, 197, 253);
    doc.text('CLINICAL SUMMARY', 10, y);
    y += 2;

    autoTable(doc, {
      startY: y,
      body: [
        ['Diagnosis', p.diagnosis || '-'],
        ['Attending Physician', p.attendingPhysician || '-'],
        ['Primary Nurse', p.primaryNurse || '-'],
        ['NEWS2 Score', String(p.news2 ?? '-')],
        ['AI Deterioration Risk', `${p.aiRiskScore ?? 0}%`],
      ],
      styles: {
        fontSize: 8,
        cellPadding: 3,
        textColor: C_LIGHT,
        fillColor: C_CARD,
        lineColor: [51, 65, 85],
        lineWidth: 0.25,
      },
      columnStyles: {
        0: { fontStyle: 'bold', textColor: C_MUTED, cellWidth: 55 },
        1: { textColor: C_WHITE },
      },
      alternateRowStyles: { fillColor: C_SLATE },
      margin: { left: 10, right: 10 },
    });

    y = (doc as any).lastAutoTable.finalY + 6;

    /* Vital Signs */
    doc.setFontSize(8);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(147, 197, 253);
    doc.text('CURRENT VITAL SIGNS', 10, y);
    y += 2;

    // NOTE: use only ASCII - special chars (subscript, symbols) break jsPDF's built-in fonts
    const vitalRows = [
      {
        param: 'Heart Rate (HR)',
        val: v.hr != null ? `${v.hr} bpm` : '-',
        ref: '60 - 100 bpm',
        bad: v.hr > 110 || v.hr < 50,
      },
      {
        param: 'SpO2 (Oxygen Sat.)',
        val: v.spo2 != null ? `${v.spo2}%` : '-',
        ref: '>= 94%',
        bad: v.spo2 < 94,
      },
      {
        param: 'Systolic BP',
        val: v.sbp != null ? `${v.sbp} mmHg` : '-',
        ref: '90 - 140 mmHg',
        bad: v.sbp < 90 || v.sbp > 160,
      },
      {
        param: 'Diastolic BP',
        val: v.dbp != null ? `${v.dbp} mmHg` : '-',
        ref: '60 - 90 mmHg',
        bad: v.dbp < 60 || v.dbp > 100,
      },
      {
        param: 'Body Temperature',
        val: v.temp != null ? `${v.temp} C` : '-',
        ref: '36.1 - 37.2 C',
        bad: v.temp > 38.5 || v.temp < 36,
      },
      {
        param: 'Respiratory Rate (RR)',
        val: v.rr != null ? `${v.rr} /min` : '-',
        ref: '12 - 20 /min',
        bad: v.rr > 25 || v.rr < 10,
      },
      {
        param: 'Mean Arterial Pressure',
        val: v.map != null ? `${v.map} mmHg` : '-',
        ref: '70 - 100 mmHg',
        bad: v.map < 65,
      },
    ];

    autoTable(doc, {
      startY: y,
      head: [['Parameter', 'Measured Value', 'Normal Range', 'Status']],
      body: vitalRows.map((r) => [r.param, r.val, r.ref, r.bad ? 'ABNORMAL' : 'Normal']),
      styles: {
        fontSize: 7.5,
        cellPadding: 2.8,
        textColor: C_LIGHT,
        fillColor: C_CARD,
        lineColor: [51, 65, 85],
        lineWidth: 0.25,
      },
      headStyles: { fillColor: C_BLUE, textColor: C_WHITE, fontStyle: 'bold' },
      alternateRowStyles: { fillColor: C_SLATE },
      columnStyles: { 3: { halign: 'center', fontStyle: 'bold' } },
      didParseCell: (data) => {
        if (data.section === 'body') {
          if (data.column.index === 3) {
            data.cell.styles.textColor =
              (data.cell.raw as string) === 'ABNORMAL' ? [252, 165, 165] : [110, 231, 183];
          }
          if (data.column.index === 1 && vitalRows[data.row.index]?.bad) {
            data.cell.styles.textColor = [252, 165, 165];
          }
        }
      },
      margin: { left: 10, right: 10 },
    });

    y = (doc as any).lastAutoTable.finalY + 6;

    /* AI Risk bar */
    const risk = p.aiRiskScore ?? 0;
    const rc = riskRGB(risk);
    const riskLabel = risk >= 70 ? 'HIGH RISK' : risk >= 40 ? 'MODERATE RISK' : 'LOW RISK';

    doc.setFillColor(...C_CARD);
    doc.roundedRect(10, y, W - 20, 24, 2, 2, 'F');

    doc.setFontSize(7.5);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(147, 197, 253);
    doc.text('AI RISK ASSESSMENT', 15, y + 7);

    doc.setFontSize(6.5);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...C_MUTED);
    doc.text('Sentinel-AI Deterioration Model  |  4-hour prediction window', 15, y + 13);

    const barX = 85,
      barW = W - barX - 22;
    doc.setFillColor(51, 65, 85);
    doc.roundedRect(barX, y + 8, barW, 6, 1, 1, 'F');
    doc.setFillColor(...rc);
    doc.roundedRect(barX, y + 8, (barW * risk) / 100, 6, 1, 1, 'F');

    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...rc);
    doc.text(`${risk}%`, barX + barW + 3, y + 14);

    doc.setFontSize(6.5);
    doc.setTextColor(...rc);
    doc.text(riskLabel, barX, y + 20);

    y += 30;

    /* Signature block */
    if (y < H - 38) {
      doc.setFillColor(...C_CARD);
      doc.roundedRect(10, y, W - 20, 30, 2, 2, 'F');

      doc.setFontSize(7.5);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(...C_MUTED);
      doc.text('AUTHORISATION & SIGNATURE', 16, y + 8);

      const sigY = y + 24;
      const sigSlots: [number, string][] = [
        [16, 'Attending Physician'],
        [W / 2 - 22, 'Primary Nurse'],
        [W - 66, 'Ward Head / Senior Clinician'],
      ];
      sigSlots.forEach(([sx, label]) => {
        doc.setDrawColor(71, 85, 105);
        doc.setLineWidth(0.3);
        doc.line(sx, sigY, sx + 50, sigY);
        doc.setFontSize(6.5);
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(...C_MUTED);
        doc.text(label, sx + 25, sigY + 4, { align: 'center' });
      });
    }

    footer();
  });

  /* Save */
  const filename =
    patients.length === 1
      ? `Sentinel_${patients[0].name.replace(/\s+/g, '_')}_${now.toISOString().slice(0, 10)}.pdf`
      : `Sentinel_PatientReport_${patients.length}pts_${now.toISOString().slice(0, 10)}.pdf`;

  doc.save(filename);
}
