import type { Patient, Alert, Ward, User, VitalReading } from './types';

function generateTrend(
  baseHr: number,
  baseSpo2: number,
  baseSbp: number,
  points = 24
): VitalReading[] {
  const now = new Date('2026-04-25T05:35:00');
  return Array.from({ length: points }, (_, i) => {
    const t = new Date(now.getTime() - (points - 1 - i) * 60 * 60 * 1000);
    const hr = Math.round(baseHr + (Math.random() - 0.5) * 18);
    const spo2 = Math.round(Math.max(85, baseSpo2 + (Math.random() - 0.5) * 4));
    const sbp = Math.round(baseSbp + (Math.random() - 0.5) * 20);
    const dbp = Math.round(sbp * 0.6 + (Math.random() - 0.5) * 8);
    const temp = parseFloat((36.5 + (Math.random() - 0.4) * 1.8).toFixed(1));
    const rr = Math.round(14 + (Math.random() - 0.5) * 8);
    const map = Math.round((sbp + 2 * dbp) / 3);
    return {
      time: t.toLocaleTimeString('en-GB', { hour: '2-digit', minute: '2-digit' }),
      hr,
      spo2,
      sbp,
      dbp,
      temp,
      rr,
      map,
    };
  });
}

export const MOCK_PATIENTS: Patient[] = [
  {
    id: 'pt-001',
    name: 'Arjun Mehta',
    age: 67,
    gender: 'M',
    bedId: 'bed-a01',
    wardId: 'ward-icu-a',
    admissionDate: '2026-04-22',
    diagnosis: 'Septic Shock',
    status: 'critical',
    news2: 11,
    aiRiskScore: 88,
    vitals: { hr: 118, spo2: 88, sbp: 82, dbp: 48, temp: 38.9, rr: 28, map: 59 },
    trend: generateTrend(110, 87, 82),
    attendingPhysician: 'Dr. Priya Sharma',
    primaryNurse: 'Nurse Kavita Rao',
  },
  {
    id: 'pt-002',
    name: 'Margaret O\'Sullivan',
    age: 74,
    gender: 'F',
    bedId: 'bed-a02',
    wardId: 'ward-icu-a',
    admissionDate: '2026-04-23',
    diagnosis: 'ARDS / COVID-19',
    status: 'critical',
    news2: 10,
    aiRiskScore: 82,
    vitals: { hr: 104, spo2: 91, sbp: 95, dbp: 58, temp: 38.4, rr: 26, map: 70 },
    trend: generateTrend(100, 91, 95),
    attendingPhysician: 'Dr. Priya Sharma',
    primaryNurse: 'Nurse James Okafor',
  },
  {
    id: 'pt-003',
    name: 'Ravi Krishnamurthy',
    age: 55,
    gender: 'M',
    bedId: 'bed-a03',
    wardId: 'ward-icu-a',
    admissionDate: '2026-04-24',
    diagnosis: 'Acute MI — Post-PCI',
    status: 'warning',
    news2: 7,
    aiRiskScore: 61,
    vitals: { hr: 92, spo2: 94, sbp: 108, dbp: 68, temp: 37.2, rr: 20, map: 81 },
    trend: generateTrend(88, 94, 108),
    attendingPhysician: 'Dr. Vikram Nair',
    primaryNurse: 'Nurse Kavita Rao',
  },
  {
    id: 'pt-004',
    name: 'Elena Vasquez',
    age: 49,
    gender: 'F',
    bedId: 'bed-b01',
    wardId: 'ward-icu-b',
    admissionDate: '2026-04-21',
    diagnosis: 'Traumatic Brain Injury',
    status: 'warning',
    news2: 6,
    aiRiskScore: 55,
    vitals: { hr: 78, spo2: 96, sbp: 148, dbp: 92, temp: 37.6, rr: 18, map: 111 },
    trend: generateTrend(76, 96, 148),
    attendingPhysician: 'Dr. Vikram Nair',
    primaryNurse: 'Nurse Sarah Chen',
  },
  {
    id: 'pt-005',
    name: 'Oluwaseun Adeyemi',
    age: 38,
    gender: 'M',
    bedId: 'bed-b02',
    wardId: 'ward-icu-b',
    admissionDate: '2026-04-25',
    diagnosis: 'Diabetic Ketoacidosis',
    status: 'watch',
    news2: 4,
    aiRiskScore: 38,
    vitals: { hr: 102, spo2: 97, sbp: 118, dbp: 72, temp: 37.1, rr: 22, map: 87 },
    trend: generateTrend(100, 97, 118),
    attendingPhysician: 'Dr. Amara Diallo',
    primaryNurse: 'Nurse James Okafor',
  },
  {
    id: 'pt-006',
    name: 'Sunita Patel',
    age: 62,
    gender: 'F',
    bedId: 'bed-b03',
    wardId: 'ward-icu-b',
    admissionDate: '2026-04-23',
    diagnosis: 'Pulmonary Embolism',
    status: 'watch',
    news2: 5,
    aiRiskScore: 44,
    vitals: { hr: 96, spo2: 95, sbp: 122, dbp: 76, temp: 37.4, rr: 21, map: 91 },
    trend: generateTrend(94, 95, 122),
    attendingPhysician: 'Dr. Amara Diallo',
    primaryNurse: 'Nurse Sarah Chen',
  },
  {
    id: 'pt-007',
    name: 'Thomas Andreessen',
    age: 71,
    gender: 'M',
    bedId: 'bed-c01',
    wardId: 'ward-icu-c',
    admissionDate: '2026-04-20',
    diagnosis: 'CHF Exacerbation',
    status: 'stable',
    news2: 3,
    aiRiskScore: 22,
    vitals: { hr: 72, spo2: 97, sbp: 132, dbp: 82, temp: 36.8, rr: 16, map: 99 },
    trend: generateTrend(70, 97, 132),
    attendingPhysician: 'Dr. Priya Sharma',
    primaryNurse: 'Nurse Kavita Rao',
  },
  {
    id: 'pt-008',
    name: 'Fatima Al-Rashidi',
    age: 44,
    gender: 'F',
    bedId: 'bed-c02',
    wardId: 'ward-icu-c',
    admissionDate: '2026-04-24',
    diagnosis: 'Post-Op Liver Resection',
    status: 'stable',
    news2: 2,
    aiRiskScore: 18,
    vitals: { hr: 68, spo2: 98, sbp: 118, dbp: 74, temp: 36.6, rr: 14, map: 89 },
    trend: generateTrend(66, 98, 118),
    attendingPhysician: 'Dr. Vikram Nair',
    primaryNurse: 'Nurse James Okafor',
  },
  {
    id: 'pt-009',
    name: 'Dmitri Volkov',
    age: 58,
    gender: 'M',
    bedId: 'bed-c03',
    wardId: 'ward-icu-c',
    admissionDate: '2026-04-22',
    diagnosis: 'GI Bleed — Post-Endoscopy',
    status: 'stable',
    news2: 2,
    aiRiskScore: 15,
    vitals: { hr: 74, spo2: 98, sbp: 124, dbp: 78, temp: 36.7, rr: 15, map: 93 },
    trend: generateTrend(72, 98, 124),
    attendingPhysician: 'Dr. Amara Diallo',
    primaryNurse: 'Nurse Sarah Chen',
  },
  {
    id: 'pt-010',
    name: 'Ananya Krishnan',
    age: 29,
    gender: 'F',
    bedId: 'bed-d01',
    wardId: 'ward-icu-d',
    admissionDate: '2026-04-25',
    diagnosis: 'Eclampsia — Post-Partum',
    status: 'warning',
    news2: 8,
    aiRiskScore: 70,
    vitals: { hr: 108, spo2: 93, sbp: 162, dbp: 104, temp: 38.1, rr: 24, map: 123 },
    trend: generateTrend(105, 93, 162),
    attendingPhysician: 'Dr. Priya Sharma',
    primaryNurse: 'Nurse Kavita Rao',
  },
];

export const MOCK_WARDS: Ward[] = [
  { id: 'ward-icu-a', name: 'ICU Alpha', hospitalId: 'hosp-1', totalBeds: 8, occupiedBeds: 7, criticalPatients: 2 },
  { id: 'ward-icu-b', name: 'ICU Beta', hospitalId: 'hosp-1', totalBeds: 8, occupiedBeds: 6, criticalPatients: 1 },
  { id: 'ward-icu-c', name: 'ICU Gamma', hospitalId: 'hosp-1', totalBeds: 10, occupiedBeds: 8, criticalPatients: 0 },
  { id: 'ward-icu-d', name: 'Cardiac ICU', hospitalId: 'hosp-2', totalBeds: 6, occupiedBeds: 5, criticalPatients: 1 },
  { id: 'ward-icu-e', name: 'Neuro ICU', hospitalId: 'hosp-2', totalBeds: 8, occupiedBeds: 4, criticalPatients: 0 },
];

export const MOCK_ALERTS: Alert[] = [
  {
    id: 'alert-001',
    patientId: 'pt-001',
    patientName: 'Arjun Mehta',
    bedId: 'bed-a01',
    wardId: 'ward-icu-a',
    wardName: 'ICU Alpha',
    type: 'Hemodynamic Instability',
    triggerMetric: 'MAP',
    triggerValue: '59 mmHg',
    normalRange: '70–100 mmHg',
    news2: 11,
    severity: 'critical',
    status: 'active',
    createdAt: '2026-04-25T05:10:00',
    assignedTo: 'Dr. Priya Sharma',
    escalationLevel: 3,
    aiGenerated: true,
    notes: 'AI prediction: 88% probability of septic shock deterioration within 2h. Norepinephrine dose adjustment recommended.',
  },
  {
    id: 'alert-002',
    patientId: 'pt-001',
    patientName: 'Arjun Mehta',
    bedId: 'bed-a01',
    wardId: 'ward-icu-a',
    wardName: 'ICU Alpha',
    type: 'Hypoxemia',
    triggerMetric: 'SpO2',
    triggerValue: '88%',
    normalRange: '≥94%',
    news2: 11,
    severity: 'critical',
    status: 'acknowledged',
    createdAt: '2026-04-25T04:48:00',
    acknowledgedAt: '2026-04-25T04:52:00',
    assignedTo: 'Nurse Kavita Rao',
    escalationLevel: 2,
    aiGenerated: false,
    notes: 'FiO2 increased to 0.8. ABG ordered.',
  },
  {
    id: 'alert-003',
    patientId: 'pt-002',
    patientName: "Margaret O'Sullivan",
    bedId: 'bed-a02',
    wardId: 'ward-icu-a',
    wardName: 'ICU Alpha',
    type: 'Respiratory Deterioration',
    triggerMetric: 'RR',
    triggerValue: '26 /min',
    normalRange: '12–20 /min',
    news2: 10,
    severity: 'critical',
    status: 'escalated',
    createdAt: '2026-04-25T05:22:00',
    assignedTo: 'Dr. Priya Sharma',
    escalationLevel: 3,
    aiGenerated: true,
    notes: 'SBAR: Situation — RR 26, SpO2 91% on CPAP 10cmH2O. Background — ARDS Day 3. Assessment — CPAP failure likely. Recommendation — Consider intubation.',
  },
  {
    id: 'alert-004',
    patientId: 'pt-003',
    patientName: 'Ravi Krishnamurthy',
    bedId: 'bed-a03',
    wardId: 'ward-icu-a',
    wardName: 'ICU Alpha',
    type: 'Cardiac Arrhythmia',
    triggerMetric: 'HR',
    triggerValue: '92 bpm (irregular)',
    normalRange: '60–100 bpm regular',
    news2: 7,
    severity: 'high',
    status: 'active',
    createdAt: '2026-04-25T05:15:00',
    assignedTo: 'Dr. Vikram Nair',
    escalationLevel: 1,
    aiGenerated: true,
    notes: 'New AF detected post-PCI. Rate control initiated.',
  },
  {
    id: 'alert-005',
    patientId: 'pt-004',
    patientName: 'Elena Vasquez',
    bedId: 'bed-b01',
    wardId: 'ward-icu-b',
    wardName: 'ICU Beta',
    type: 'Hypertensive Crisis',
    triggerMetric: 'SBP',
    triggerValue: '148 mmHg',
    normalRange: '90–140 mmHg',
    news2: 6,
    severity: 'high',
    status: 'acknowledged',
    createdAt: '2026-04-25T04:30:00',
    acknowledgedAt: '2026-04-25T04:35:00',
    assignedTo: 'Dr. Vikram Nair',
    escalationLevel: 1,
    aiGenerated: false,
    notes: 'Labetalol 10mg IV given. Repeat BP in 15 min.',
  },
  {
    id: 'alert-006',
    patientId: 'pt-005',
    patientName: 'Oluwaseun Adeyemi',
    bedId: 'bed-b02',
    wardId: 'ward-icu-b',
    wardName: 'ICU Beta',
    type: 'Tachycardia',
    triggerMetric: 'HR',
    triggerValue: '102 bpm',
    normalRange: '60–100 bpm',
    news2: 4,
    severity: 'moderate',
    status: 'active',
    createdAt: '2026-04-25T05:28:00',
    assignedTo: 'Nurse James Okafor',
    escalationLevel: 1,
    aiGenerated: false,
    notes: '',
  },
  {
    id: 'alert-007',
    patientId: 'pt-006',
    patientName: 'Sunita Patel',
    bedId: 'bed-b03',
    wardId: 'ward-icu-b',
    wardName: 'ICU Beta',
    type: 'Hypoxemia',
    triggerMetric: 'SpO2',
    triggerValue: '95%',
    normalRange: '≥96%',
    news2: 5,
    severity: 'moderate',
    status: 'resolved',
    createdAt: '2026-04-25T03:10:00',
    acknowledgedAt: '2026-04-25T03:14:00',
    resolvedAt: '2026-04-25T04:00:00',
    assignedTo: 'Nurse Sarah Chen',
    escalationLevel: 0,
    aiGenerated: false,
    notes: 'O2 therapy increased. Resolved.',
  },
  {
    id: 'alert-008',
    patientId: 'pt-010',
    patientName: 'Ananya Krishnan',
    bedId: 'bed-d01',
    wardId: 'ward-icu-d',
    wardName: 'Cardiac ICU',
    type: 'Hypertensive Emergency',
    triggerMetric: 'MAP',
    triggerValue: '123 mmHg',
    normalRange: '70–100 mmHg',
    news2: 8,
    severity: 'high',
    status: 'active',
    createdAt: '2026-04-25T05:30:00',
    assignedTo: 'Dr. Priya Sharma',
    escalationLevel: 2,
    aiGenerated: true,
    notes: 'AI: Eclampsia recurrence risk 70% within 4h. MgSO4 protocol review recommended.',
  },
  {
    id: 'alert-009',
    patientId: 'pt-010',
    patientName: 'Ananya Krishnan',
    bedId: 'bed-d01',
    wardId: 'ward-icu-d',
    wardName: 'Cardiac ICU',
    type: 'Tachypnea',
    triggerMetric: 'RR',
    triggerValue: '24 /min',
    normalRange: '12–20 /min',
    news2: 8,
    severity: 'moderate',
    status: 'active',
    createdAt: '2026-04-25T05:31:00',
    assignedTo: 'Nurse Kavita Rao',
    escalationLevel: 1,
    aiGenerated: false,
    notes: '',
  },
  {
    id: 'alert-010',
    patientId: 'pt-007',
    patientName: 'Thomas Andreessen',
    bedId: 'bed-c01',
    wardId: 'ward-icu-c',
    wardName: 'ICU Gamma',
    type: 'Fluid Overload Risk',
    triggerMetric: 'HR',
    triggerValue: '72 bpm (trending up)',
    normalRange: '60–80 bpm',
    news2: 3,
    severity: 'low',
    status: 'resolved',
    createdAt: '2026-04-25T02:00:00',
    acknowledgedAt: '2026-04-25T02:05:00',
    resolvedAt: '2026-04-25T03:30:00',
    assignedTo: 'Nurse Kavita Rao',
    escalationLevel: 0,
    aiGenerated: true,
    notes: 'Diuretic dose adjusted. Resolved.',
  },
  {
    id: 'alert-011',
    patientId: 'pt-008',
    patientName: 'Fatima Al-Rashidi',
    bedId: 'bed-c02',
    wardId: 'ward-icu-c',
    wardName: 'ICU Gamma',
    type: 'Temp Spike',
    triggerMetric: 'Temp',
    triggerValue: '38.2°C',
    normalRange: '36.1–37.2°C',
    news2: 2,
    severity: 'low',
    status: 'acknowledged',
    createdAt: '2026-04-25T04:15:00',
    acknowledgedAt: '2026-04-25T04:20:00',
    assignedTo: 'Nurse James Okafor',
    escalationLevel: 0,
    aiGenerated: false,
    notes: 'Blood cultures drawn. Antipyretics given.',
  },
];

export const MOCK_USERS: User[] = [
  { id: 'user-001', name: 'Dr. Priya Sharma', role: 'doctor', hospitalId: 'hosp-1', wardId: 'ward-icu-a', email: 'priya.sharma@sentinel.icu' },
  { id: 'user-002', name: 'Dr. Vikram Nair', role: 'doctor', hospitalId: 'hosp-1', wardId: 'ward-icu-b', email: 'vikram.nair@sentinel.icu' },
  { id: 'user-003', name: 'Nurse Kavita Rao', role: 'nurse', hospitalId: 'hosp-1', wardId: 'ward-icu-a', email: 'kavita.rao@sentinel.icu' },
  { id: 'user-004', name: 'Nurse James Okafor', role: 'nurse', hospitalId: 'hosp-1', wardId: 'ward-icu-b', email: 'james.okafor@sentinel.icu' },
  { id: 'user-005', name: 'Admin Sys', role: 'admin', hospitalId: 'hosp-1', wardId: 'ward-icu-a', email: 'admin@sentinel.icu' },
];

export const WARD_ALERT_FREQUENCY = [
  { ward: 'ICU Alpha', critical: 4, high: 3, moderate: 2, low: 1 },
  { ward: 'ICU Beta', critical: 1, high: 2, moderate: 3, low: 2 },
  { ward: 'ICU Gamma', critical: 0, high: 1, moderate: 1, low: 3 },
  { ward: 'Cardiac ICU', critical: 2, high: 2, moderate: 2, low: 0 },
  { ward: 'Neuro ICU', critical: 0, high: 0, moderate: 1, low: 1 },
];